# Le dice al compilador que use el ecosistema moderno de Android
android.useAndroidX=true

# Convierte automáticamente cualquier librería vieja a la versión nueva
android.enableJetifier=true

# Le damos 2GB de RAM a la máquina virtual de GitHub para que compile más rápido
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8