name: Compilar APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Dar permisos de ejecución
      run: chmod +x gradlew
      
    - name: Compilar APK
      run: ./gradlew assembleDebug
      
    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: Modula-APK
        path: app/build/outputs/apk/debug/app-debug.apk
